# -*- coding: utf-8 -*-
"""Merge the returned S1-S3 adjudication workbooks into the analysis inputs.

The workbooks were generated by build_review_checklists.py and filled in by the
authors (S1 and S2 by the surgical team; S3 by two independent readers, A in the
main workbook and B in the reader-B workbook). This script only transcribes
those decisions; it makes none of its own except the five S3 cells on which the
readers disagreed, whose adjudication the authors approved and which are listed
in ADJ below.

Writes
  review_exclusions.csv   children and reports removed from the analysis, and
                          the one index examination that changed as a result
  us_manual_coding.csv    consensus coding of the 12 ultrasound content items
  review_agreement.json   per-item agreement of the two readers (Cohen's kappa)

core.py and usaudit4.py read the two CSV files.
"""
import json
import pandas as pd

MAIN = 'review_returns/审稿核对表_S1-S3_已填.xlsx'
READER_B = 'review_returns/S3超声报告阅读_阅读者乙_已填.xlsx'

# ---------- S1: was malrotation confirmed at the anchor operation? ----------
s1 = pd.read_excel(MAIN, sheet_name='S1_锚定手术判定')
S1_REASON = {'非本次手术确认（排除）': 'malrotation not confirmed at the anchor operation',
             '复发再次手术（单独讨论）': 'anchor operation was a reoperation after earlier malrotation surgery'}
assert s1['【填】判定'].value_counts().to_dict() == {
    '本次手术确认肠旋转不良（保留）': 19, '复发再次手术（单独讨论）': 9, '非本次手术确认（排除）': 6}
rows = [{'kind': 'child', '科研患者编号': int(r.患者编号), 'mod': '', '检查时间': '', 'label': '',
         'reason': S1_REASON[r._11]}
        for r in s1.itertuples() if r._11 in S1_REASON]

# ---------- S2: was the index examination preoperative? ----------
s2 = pd.read_excel(MAIN, sheet_name='S2_术前时间核对')
MOD = {'超声': 'US', '上消化道造影': 'UGI', 'CT': 'CT'}
S2_REASON = {'术后（剔除）': 'issued after the operation on the day of surgery',
             '排除（与本次手术病程无关）': 'unrelated to the illness that led to the operation'}
KEEP = {'术前（保留）', '保留', '无法判断'}
assert set(s2['【填】判定']) <= KEEP | set(S2_REASON)
# the one undetermined report (4310607, 21:45) is an empty great-vessel report
# pooled with the same evening's bedside study; it carries no text, so it is kept
und = s2[s2['【填】判定'] == '无法判断']
assert len(und) == 1 and int(und['患者编号'].iloc[0]) == 4310607 and pd.isna(und['检查结论'].iloc[0])
for r in s2[s2['【填】判定'].isin(S2_REASON)].itertuples():
    rows.append({'kind': 'report', '科研患者编号': int(r.患者编号), 'mod': MOD[r.模态],
                 '检查时间': pd.Timestamp(r.检查时间).isoformat(sep=' '), 'label': '',
                 'reason': S2_REASON[r._13]})
# Removing 1426267's postoperative UGI makes its earlier UGI (4 May 2020) the
# index examination. Its conclusion ("1. low incomplete intestinal obstruction
# considered; 2. gastric volvulus [胃翻转]") names neither malrotation nor
# midgut volvulus, and the published rule set (classifier.py) also returns 0.
rows.append({'kind': 'relabel', '科研患者编号': 1426267, 'mod': 'UGI',
             '检查时间': '2020-05-04 09:20:53', 'label': 0,
             'reason': 'new index examination after removal of the postoperative report; '
                       'conclusion names neither malrotation nor midgut volvulus'})
ex = pd.DataFrame(rows)
assert (ex['kind'] == 'child').sum() == 15 and (ex['kind'] == 'report').sum() == 4
ex.to_csv('review_exclusions.csv', index=False)

# ---------- S3: two independent readings of the ultrasound index episodes ----------
A = pd.read_excel(MAIN, sheet_name='S3_超声报告阅读_甲')
B = pd.read_excel(READER_B, sheet_name='S3_超声报告阅读_乙')
ITEMS = {'十二指肠第三段（水平部/横部）': 'd3', '十二指肠空肠交界（屈氏韧带）': 'djj',
         '提及十二指肠（任何形式）': 'duodenum', '肠系膜上动、静脉位置关系': 'sma_smv',
         '明确写出动静脉换位/倒置': 'inversion', '写明检查前给液（口服或胃管注入）': 'fluid',
         '动态观察': 'dynamic', '加压或逐级加压': 'compress', '回盲部位置': 'cecum',
         '使用彩色多普勒': 'doppler', '漩涡征（阳性描述，未被否定）': 'whirl_pos',
         '肠气干扰显示（明确写出）': 'gas_limit'}
assert len(A) == len(B) == 119 and (A['患者编号'] == B['患者编号']).all()
for d in (A, B):
    assert d[list(ITEMS)].isin(['是', '否']).all().all()
# adjudication of the disagreements, approved by the authors
ADJ = {(3724539, '写明检查前给液（口服或胃管注入）'): '否',
       (3724539, '动态观察'): '是',
       (3813706, '漩涡征（阳性描述，未被否定）'): '是',
       (4276724, '漩涡征（阳性描述，未被否定）'): '是',
       (8673539, '漩涡征（阳性描述，未被否定）'): '否'}
dis = {(int(A.at[i, '患者编号']), c) for i in A.index for c in ITEMS if A.at[i, c] != B.at[i, c]}
assert dis == set(ADJ), dis
C = A[['患者编号']].rename(columns={'患者编号': '科研患者编号'}).copy()
for c, k in ITEMS.items():
    C[k] = [(ADJ.get((int(p), c)) if a != b else a) == '是'
            for p, a, b in zip(A['患者编号'], A[c], B[c])]
C['d3_or_djj'] = C['d3'] | C['djj']
C.to_csv('us_manual_coding.csv', index=False)


def kappa(a, b):
    a, b = (a == '是').astype(int), (b == '是').astype(int)
    po = (a == b).mean()
    pe = a.mean() * b.mean() + (1 - a.mean()) * (1 - b.mean())
    return None if pe == 1 else (po - pe) / (1 - pe)


AG = {k: {'agree': int((A[c] == B[c]).sum()), 'n': len(A),
          'kappa': kappa(A[c], B[c]),
          'reader_A': int((A[c] == '是').sum()), 'reader_B': int((B[c] == '是').sum()),
          'consensus': int(C[k].sum())} for c, k in ITEMS.items()}
json.dump({'items': AG, 'cells': len(A) * len(ITEMS), 'disagreeing_cells': len(dis),
           'disagreeing_episodes': len({p for p, _ in dis})},
          open('review_agreement.json', 'w'), ensure_ascii=False, indent=1)
print(ex.to_string())
for k, v in AG.items():
    kap = 'n/a' if v['kappa'] is None else f"{v['kappa']:.2f}"
    print(f"{k:10s} A {v['reader_A']:3d}  B {v['reader_B']:3d}  agree {v['agree']}/{v['n']}  kappa {kap}  consensus {v['consensus']}")
